# Code to Embbed the data
import numpy as np

from sentence_transformers import SentenceTransformer
from dataclasses import dataclass


@dataclass
class embedd_model_configs:
    model_repo_id: str="sentence-transformers/all-MiniLM-L6-v2"

class create_embeddings:
    def __init__(self):
        self.configs = embedd_model_configs

    def encode_data(self, data):
        embedding_model = SentenceTransformer(self.configs.model_repo_id)
        embedded_data = embedding_model.encode(data).astype(np.float32)
        return embedded_data
    

# if __name__ == "__main__":
#     chunks = ['AQUARIUM FISH AND THEIR MAINTENANCE \n(e-contents prepared by- Prof. S.P. Trivedi, University of Lucknow) \n \nB. MAINTENANCE OF AQUARIUM FISHES \n \nWHAT IS AN AQUARIUM? \nAn aquarium is a glass container which displays the aquatic organisms in a \nsimulated natural environment by introducing aquatic plants, rocks, gravels, \nartificial decorative etc.  Maintenance of physico-chemical and biological \nparameters of water inside the aquaria is of utmost importance. Different types \nof equipments are required for controlling aeration, water movement, \ntemperature, suspended organic matter, illumination etc inside the aquaria. \nUtmost care should be taken while feeding aquarium fishes. Over feeding is \nalways harmful to fishes. \n \nIn effect, an aquarium is a biological entity. Each of its elements – water, \nglass, light, sand, gravel, plants, fish, make a harmonious whole, with the \nsame ecological balance as exists in nature. \nA. \nSELLECTION OF A TANK \nA tank with a water capacity of 125-250 L is most conventional. An ',
#  'appropriate \nsize would be an 80 cm tank (80x40x40cm) or a meter size tank \n(100x50x50cm). The most popular size of home aquarium is 60 cm length x 30 \ncm width x 40 cm height, with a capacity of 57 L (15 gallons). Never the less, \naquaria size depends much on   availability of space and point of attraction. \nAquaria Tanks are usually measured as =    Length x Depth x Height  \nAquarium tank is of prime importance.  An aquarist must consider its shape, \nsize and material used \nTanks may be of several kinds: Metal frame tank, Plexi-glass tank , or All glass \ntank  \nB. AQUARIA TYPES \n \nBased on water regime contained in the aquaria they may be of two types: \n \n1. Fresh water aquaria, and  \n \n2. Marine water aquaria \nTYPES OF AQUARIA\nIn a broad sense, aquaria are divided in \ntwo categories:\nMarine aquaria\nFresh water aquaria\nAquarium\nthat\nhouses\nfish\nand\nplants\nof\nfreshwater\nworld.\nFreshwater contains small amount\nof salts and gases in solution. Fresh\nwater may be classed as ‘hard’ or\n‘soft’ according to the sodi',
#  'um and\ncalcium it contains in compounds.\nMarine aquarium is a biological \nentity which houses marine flora \nand fauna in a harmony. Sea water \ndiffers from fresh water by its salt \ncontent.\n \nC. AQUARIA BOTTOM \n \nThe base of an aquarium is known as bottom. Over this base aquaria  \nbed is prepared. This serves following two basic purposes:  \n• \nTo make the fish feel more at home, and  \n• \nTo provide a growing medium for aquatic plants.  \n Unless a particular species of fish has special requirements, the \ncomposition of the bed is mostly governed by the needs of the plant to be \nplaced in aquaria bed. Plants suitable for the purpose can be grouped in \nfollowing categories:  \n\uf0b7 Rooted plants – Vallisneria, Sagittaria.    \n\uf0b7 Cuttings – Fanwort, Hygrophilia,Ceratophyllum, Limnophila. \n\uf0b7 Floating Plants – Lemna, Riccia, Salvinia  \n \nD. AQUARIA STAND, HOOD AND PLACEMENT \n \n\uf0b7 Aquaria stand is wooden/metallic structure on which aquarium is \nplaced. This must be flat and level and capable of carrying the load \nof entir',
#  'e set.  \n\uf0b7 Aquaria hood is the top most covering of an aquarium to keep the \nfishes confined in the tank, minimize water loss by evaporation, \noffers more protection against intruders and helps in light \nattachment.  \n\uf0b7 Placement of an aquarium should be intended to receive \nmaximum amount of light:  \n \nE. AQUARIA FILTERS \n \n             Harmful substance like ammonia and nitrates are \nregularly produced mainly through fish metabolism as excretory \nproduct. They keep on accumulating in the aquaria water. At \ntimes, they may exceed the carrying capacity of aquaria water and \ncross the lethal limits and eventually poison the fish. That is why \nproper arrangements should be there for removing these harmful \nsubstances and getting clear water in an aquarium.  This can be \nachieved by the process of filtration and the devices employed for \nthe purpose are known as filters.                 \n             Aquaria filters are of three types:  \n1. Mechanical filters \n2. Chemical filters and \n3. Biological filters \nBiol',
#  'ogical filter is again broadly divided into 3 types: \n\uf0b7 UG filters b) Foam filters and c) Power filters. \nFunctions of filters:  \n\uf0b7 Filters play a significant role in purification of aquaria water with \nthe help bacteria.  When ammonia loaded water is passed through \nthe gravel bed of filter, it is subjected to the action of aerobic \nnitrifying bacteria that oxidize toxic ammonia into nitrite by \nNitrosomonas bacteria. The nitrites get further oxidized by \nNitrobacter group of bacteria into nitrates which are less toxic to \nthe fish. They finally gets absorbed by the plants.  \n \n\uf0b7  The aquaria water is quite likely to get polluted due to the \nexcretory products of fish, plants, dead organisms and uneaten \nfood rich in nitrogen compounds, filters get rid of them by their \nbiological and mechanical actions. \n \nF. DECORATION OF AQUARIA \n \nOnce an aquarium is well set and properly placed, now the time comes \nfor its decoration. Uninterrupted supply of oxygen is of prime concern in an \naquarium. Normally stone dif',
#  'fusers, connected to an air pump by a plastic \ntube, are placed inside the aquarium. However, to give aquaria an \nattractive look a number of decorative toys are available in market. They \ninclude plastic bubbles in the guise (appearance) of mermaid (sea creature), \nunder water diver, oyster shells, angler, human skull, frog etc. Coloured \nmarble stor sea bottom ones can be spread over the sand bottom of the \naquaria. Sometimes a colorful picture of sea strata or sea bottom may be \nplaced at back side of an aquarium to look it more attractive. \n \nG. WATER FILLING \n \nWater contributes the immediate environment for the fishes. Aquarium \nshould be filled with clear potable water. If tap water is chlorinated, it has \nto be aerated overnight before adding to an aquarium. \n \nH. FISHES OF CHOICE \nAfter maintenance of adequate water load in the aquarium (2.5cms of \nfish to each gallon of water) fishes of choice should be introduced in the \naquarium. Aquarium fishes are both exotic and indigenous).Some of the \npopular',
#  ' aquarium fishes are listed below:  \n \n(1)      Barbus tetrazona and B.ticto  \n(2)      Betta splendens  \n(3)      Botia dareo  \n(4)      Carassius auratus (goldfish)  \n(5)      Colisa lalia  \n(6)      Colisa chuna  \n(7)      Cyprinus carpio  \n(8)      Gambusia affinis  \n(9)      Hemichromis bimaculatus  \n(10)  Lebistes reticulates (guppy)  \n(11)  Macropodus opercularis  \n(12)  Nemacheilus aureus  \n(13)  Poecilia reticulata  \n(14)  \nPterophyllum scalare and P.eimekei (angelfish)  \n(15)  \nTilapia macrocephala  \n(16)  \nTrichogaster trichopterus  \n(17) \n Puntius ticto  \n \nI. PHYSICO- CHEMICAL REQUIREMENTS OF AQUARIA WATER \n \nWater plays an important role in survival and growth of fishes. Physico-\nchemical regime of aquaria water should be maintained well within the \nrecommended limits, viz., Temperature of 76 to 80 °F, pH ‐ 7.6 to 8.4 and \nSpecific Gravity ‐ 1.002 to 1.007 (optimal). Using marine synthetic salt will \nimprove the success in the brackish water setup compared to marine \nsetup. The synthetic salt co',
#  'ntains all the trace elements and buffers \nrequired to give the correct pH. The salt should be mixed at half the \nrecommended strength.  \n \nJ. FOOD AND FEEDING OF AUARIUM FISHES \n  \nMost of the aquarium fish are carnivores and their diet should reflect this. \nIn most cases, lots of live food will be required but this depends upon the \nchoice of species to be kept. Synthetic aquaria foods are available in \nmarket. Overfeeding should always be avoided. \n \nFood for aquarium fishes \n2. live food-\nit can be divided into two \ngroups, those that occur \nnaturally in ponds and \nstreams (natural live \nfoods) and those that are \nusually terrestrial (Brine \nShrimps, Atremia, being \nan exception) and are \ncultured or collected  \n(cultured live foods).\nThe food for aquarium \nfishes maybe grouped into \nthree categories-\n1. Commercial food-\nTop quality commercial \nfood normally contains \nvery little percentage \nof moisture which  \nmay be 2-3% with \ncorrespondingly higher \nconcentrations of \nproteins, \ncarbohydrates, lipids, ',
#  '\nvitamins and minerals.\n3. natural live food- in \naddition to plants \navailable in the \naquarium, it also \nincludes Daphnia, \nMosquito, Midge, Gnat \nlarvae, Drosophila, \nBrine Shrimps, \nEarthworms, \nMicroworms, \n(Anguillula sillusiae), \nTubifex, Cyclops etc. \n \nNutrients requirements of \nornamental fishes\nCrude Protein level-30-45%\nCrude lipid-4-8%\nCarbohydrate-30-50%\n \nNutrients requirements for Young and \nAdult Ornamental Fishes\nYoung Ornamental \nFishes\nAdult or Brood \nOrnamental Fishes\nProtein-40-50%\nLipid-4-6%\nCarbohydrate-40-50%\nProtein-30-35%\nLipid-6-8%\nCarbohydrate-40-50%\n1% vitamins –minerals  could also be added w ith above given nutrients.\n \n \n• \nImportant points to be looked into are:\ni)\nRegular water change (20-30% every two or four weeks)\nii) Cleaning of algal scum from the glass at periodical interval.\niii) Removal of dead fishes, if noticed inside the aquarium.\niv) Racking the surface layer of the substrate and removal of dirt\netc. by vacuum device every week\nv) Pruning of excess plant growth, ',
#  'when noticed\nvi)If aquarium water turns cloudy after one or two months, it\nindicates the need to change water.\nvii)Water loss caused by evaporation should be made up once a\nweek\nRegular maintenance : \n \n• \nK. IMPORTANT PERCAUTIONS FOR MAINENANCE OF AQUARIA \n• \nThe aquarium should not be left uncared for a long time.  \n• \nDo not over feed the aquarium fishes.  \n• \nOnce the aquarium is set and balanced, the water should not be changed \nunless it tends to become turbid or cloudy. When the level of water falls \nin course of time, it should be restored by addition of some rain water or \nchorine free tap water.  \n• \nOvercrowding of fishes should always be avoided.  \n• \nFor tropical fishes, a temperature of around 720 F and pH of around 7 - \n7.2 is ideal.  \n• \nIn changing the water of aquarium, a constant flow should be \nmaintained with help of tubes.  \n• \nAerator should also be frequently operated.  \n• \nFishes should be subjected to KMnO4 or CuSO4 bath before keeping them \nin aquarium.  \n• \nAquarium should be fille',
#  'd by water to about three fourth of its capacity.   \n• \nOne type of food should not be used.  \n• \n Infected fishes should be immediately removed.  \n• \n An aquarium should always be provided with a cover.  \n \n \n  \n \n  \n \n \n']
    

#     embeddings = create_embeddings().encode_data(chunks)
#     print(embeddings)